{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-golem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/golem_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/golem/golem_{{ version }}.tar.gz
  sha256: 86d66415cb117c7a0ad186f174c1d3482565266cbc8b226f9a6853bdf1973f1d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-attempt >=0.3.0
    - r-cli >=2.0.0
    - r-config
    - r-crayon
    - r-desc
    - r-fs
    - r-here
    - r-htmltools
    - r-pkgload
    - r-roxygen2
    - r-rstudioapi
    - r-shiny >=1.5.0
    - r-usethis >=1.6.0
    - r-yaml
  run:
    - r-base
    - r-attempt >=0.3.0
    - r-cli >=2.0.0
    - r-config
    - r-crayon
    - r-desc
    - r-fs
    - r-here
    - r-htmltools
    - r-pkgload
    - r-roxygen2
    - r-rstudioapi
    - r-shiny >=1.5.0
    - r-usethis >=1.6.0
    - r-yaml

test:
  commands:
    - $R -e "library('golem')"           # [not win]
    - "\"%R%\" -e \"library('golem')\""  # [win]

about:
  home: https://github.com/ThinkR-open/golem
  license: MIT
  summary: An opinionated framework for building a production-ready 'Shiny' application. This package contains a series of tools for building a robust 'Shiny' application from start to finish.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: golem
# Title: A Framework for Robust Shiny Applications
# Version: 0.1
# Authors@R: c(person(given = "Vincent", family = "Guyader", role = c("cre", "aut"), email = "vincent@thinkr.fr", comment = c(ORCID = "0000-0003-0671-9270")), person(given = "Colin", family = "Fay", role = "aut", email = "contact@colinfay.me", comment = c(ORCID = "0000-0001-7343-1846")), person(given = "Sebastien", family = "Rochette", role = "aut", email = "sebastien@thinkr.fr", comment = c(ORCID = "0000-0002-1565-9313")), person(given = "Cervan", family = "Girard", role = "aut", email = "cervan@thinkr.fr", comment = c(ORCID = "0000-0002-4816-4624")), person(given = "ThinkR", role = "cph"))
# Description: An opinionated framework for building a production-ready 'Shiny' application. This package contains a series of tools for building a robust 'Shiny' application from start to finish.
# License: MIT + file LICENSE
# URL: https://github.com/ThinkR-open/golem
# BugReports: https://github.com/ThinkR-open/golem/issues
# Depends: R (>= 3.0)
# Imports: attempt, cli, crayon, desc, dockerfiler, DT, glue, htmltools, pkgload, processx, remotes, rlang, roxygen2, rsconnect, rstudioapi, shiny, stats, stringr, testthat, tools, usethis, utils, yesno
# Suggests: covr, knitr, pkgdown, purrr, rcmdcheck, rmarkdown, withr
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-19 09:00:08 UTC; Vincent
# Author: Vincent Guyader [cre, aut] (<https://orcid.org/0000-0003-0671-9270>), Colin Fay [aut] (<https://orcid.org/0000-0001-7343-1846>), Sebastien Rochette [aut] (<https://orcid.org/0000-0002-1565-9313>), Cervan Girard [aut] (<https://orcid.org/0000-0002-4816-4624>), ThinkR [cph]
# Maintainer: Vincent Guyader <vincent@thinkr.fr>
# Repository: CRAN
# Date/Publication: 2019-08-05 15:50:02 UTC
