bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: fRTKa2Qrid0fcnHw5XuH+IMhf2ARl8RMyLVsUEWgIeoToB3KTv9fEbwXCsn7iQrSiAXr6fyKboPoZkTsSGOXG3Ghi2Qb8V9xAg3wbhFlwFy9F+tmceuTt9hKqAoagesNupRt52U+ZAKAvCHNO+FZGxy3Cj1RDWDxxyroi3npnAdm4LzJB1Gecdw5uqQz265WC2gD0xyMN5h9LGczAWQ0Dw2KseWYYQ2hNpSP44OeHLfpmECt8176nTc3eZN4KIAOwKrYV3+l/EcJAzGPYFfW+DFUEDuUO5B5y6jCZmLORo2SWzq7ChHEJgbBDYI7V5Cemo5lmuyX6kgWgURFlX6hFfzNjk6Yug+gR2nMztvOxwTsuCIEDFP+VR51TYxh737o9Yw1OVtTkOQIWRnoXM8qfBUYgFyBqXukoie5tDi8xjON1JJ9SBqjoDw2J94al6RgfFHsvc5iMgRJinjSnXeNkcOKj5aW2qAzQxv207hIy+n1oSM1yDvd5X+lYSuhSlwAn3eQckM6hOFtsLrRRN3Ii3omUfbSw3QKlJJ7C9x6haGfZMtv/I1fykIMtM3gHeWeK4w8CRjhmWWOI9MY3IL/ExkHcyV8N2khMdhX1VI6v8qlun8VKeBHzuZ+2ZYzHkWh+CXqY+Aa/7D5Yqq1sLFjAEcH6mt4VPZ1glAHGkvRdsk=
conda_forge_output_validation: true
